fun main() {
    println("Lista de Modelos")
    println("Inmutables")
    val modelos = listOf("Galaxy S25", "iPhone 16", "Redmi Note 13", "Mate 60", "Edge 50")
    println(modelos)
    println("Size: ${modelos.size}")
    println("Mostrar el elemento indice 0: ${modelos[0]}")
    println("Mostrar el primer elemento: ${modelos.first()}")
    println("Mostrar el ultimo elemento: ${modelos.last()}")

    println("Mostrar el elemento indice 2: ${modelos.get(2)}")
    println("Mostrar contenido segun indice: ${modelos.indexOf("iPhone 16")}")
    println("Verificar existencia de un elemento: ${modelos.contains("Edge 50")}")
    println("Verificar existencia de un elemento: ${"Pixel 9" in modelos}")
    println("Sublista: ${modelos.subList(1, 4)}")
    println("Tomar primeros 2 elementos: ${modelos.take(2)}")
    println("Suprimir tres primeros elemento: ${modelos.drop(3)}")
    println("Tomar los ultimos dos elementos: ${modelos.takeLast(2)}")
    println(modelos)
    println("Mutables")
    val marcas = mutableListOf("Samsung", "Apple", "Xiaomi", "Huawei")
    println(marcas)
    marcas.add("Motorola")
    println(marcas)
    marcas.add(1, "OnePlus")
    println(marcas)
    marcas.remove("Xiaomi")
    println(marcas)
    marcas[1] = "Google"
    println(marcas)

    println("Array deque")
    val precios = ArrayDeque<Int>()
    println(precios)
    precios.addFirst(699)
    println(precios)
    precios.addFirst(999)
    println(precios)
    precios.addLast(499)
    println(precios)
    precios.removeFirst()
    println(precios)
    precios.removeLast()
    println(precios)
}
