fun main() {
    println("Set - Accesorios compatibles")
    println("Inmutables")
    val accesorios = setOf("funda", "cargador", "audifonos", "protector", "cargador", "funda")
    println(accesorios)
    println("Compatibilidad de Conjuntos")
    val samsungAcc = setOf("funda", "cargador", "smartwatch")
    println("Samsung $samsungAcc")
    val appleAcc = setOf("funda", "airpods", "smartwatch")
    val xiaomiAcc = setOf("funda", "cargador", "smartband")
    println("Apple $appleAcc")
    println("union ${appleAcc union samsungAcc}")
    println("interseccion ${appleAcc intersect samsungAcc}")
    println("interseccion ${xiaomiAcc intersect samsungAcc}")
    println("substraccion ${appleAcc subtract samsungAcc}")
    println("interseccion ${appleAcc subtract xiaomiAcc}")
    println("Samsung $samsungAcc")
    println("Apple $appleAcc")

    println("Set Mutables")
    val colores = mutableSetOf("negro", "blanco", "azul")
    println(colores)
    colores.add("negro")
    println(colores)
    colores.add("rojo")
    println(colores)
    colores.remove("blanco")
    println(colores)
    println("Verificar si un color existe ${"negro" in colores}")
    println("Verificar si un color existe ${"verde" in colores}")
}
